# Generated by Django 5.2.16 on 2026-08-08 13:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='budget_range',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='consent',
            field=models.BooleanField(default=False, help_text='Consent to be contacted.'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='locale',
            field=models.CharField(choices=[('fa', 'Persian'), ('en', 'English'), ('ar', 'Arabic')], default='en', max_length=5),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='preferred_contact',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('any', 'Email or phone')], default='any', max_length=20),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='project_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='request_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='service_category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='website',
            field=models.CharField(blank=True, help_text='Honeypot field — never shown to users.', max_length=255),
        ),
    ]
