/** Marketing Component Library — master barrel. */
export { Hero, type HeroProps } from "./hero"
export { StatCard, StatGrid } from "./statistics"
export { ServiceCard, ServiceGrid, ServiceIcon, type ServiceCardProps } from "./services"
export { ProjectCard, ProjectGrid, TechnologyChip, GalleryPreview, type ProjectCardProps } from "./projects"
export { ArticleCard, ArticleGrid, CategoryBadge, ReadingTime, type ArticleCardProps } from "./articles"
export { ERPFeatureCard, ERPModules, ERPTimeline, ERPArchitecturePlaceholder, type ERPFeatureCardProps } from "./erp"
export { Milestone, VerticalTimeline, HorizontalTimeline, type MilestoneProps } from "./timeline"
export { TestimonialCard, TestimonialGrid, type TestimonialCardProps } from "./testimonials"
export { LogoCloud, InfiniteLogoSlider } from "./partners"
export { FAQAccordion, FAQSearch, FAQCategoryFilter, type FAQItem } from "./faq"
export { CTA, LargeCTA, SplitCTA, GradientCTA } from "./cta"
export { ContactCard, OfficeCard, MapPlaceholder } from "./contact"
export { EnterpriseFooter } from "./footer"
export { SectionHeader, RevealContainer, GlassPanel, SpotlightContainer, AnimatedDivider, GlowBorder, FloatingBadge } from "./common"
export type { SectionHeaderProps, RevealContainerProps } from "./common"
