# Generated by Django 5.2.16 on 2026-08-03 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_library', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('title_fa', models.CharField(blank=True, max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('title_ar', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(allow_unicode=True, help_text='URL identifier; Unicode (Arabic/Persian) characters are allowed.', max_length=255, unique=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='projects.projectcategory')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project category',
                'verbose_name_plural': 'Project categories',
                'ordering': ['sort_order', 'title_en'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('title_fa', models.CharField(blank=True, max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('title_ar', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(allow_unicode=True, help_text='URL identifier; Unicode (Arabic/Persian) characters are allowed.', max_length=255, unique=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('short_description_fa', models.TextField(blank=True)),
                ('short_description_en', models.TextField(blank=True)),
                ('short_description_ar', models.TextField(blank=True)),
                ('description_fa', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_public', models.BooleanField(db_index=True, default=True)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('meta_title', models.CharField(blank=True, help_text='Recommended length: 60 characters.', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='Recommended length: 155 characters.', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('canonical_url', models.URLField(blank=True, max_length=500)),
                ('client', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('live_url', models.URLField(blank=True)),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_covers', to='media_library.mediafile')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('og_image', models.ForeignKey(blank=True, help_text='OpenGraph sharing image.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_og_images', to='media_library.mediafile')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='projects.projectcategory')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-end_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('alt_text_fa', models.CharField(blank=True, max_length=255)),
                ('alt_text_en', models.CharField(blank=True, max_length=255)),
                ('alt_text_ar', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_cover', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_images', to='media_library.mediafile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project image',
                'verbose_name_plural': 'Project images',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('title_fa', models.CharField(blank=True, max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('title_ar', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(allow_unicode=True, help_text='URL identifier; Unicode (Arabic/Persian) characters are allowed.', max_length=255, unique=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('icon', models.CharField(blank=True, help_text='Icon identifier (e.g. SVG sprite key) — UI-level only.', max_length=255)),
                ('website', models.URLField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Technology',
                'verbose_name_plural': 'Technologies',
                'ordering': ['sort_order', 'title_en'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(blank=True, related_name='projects', to='projects.technology'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', 'is_public', 'published_at'], name='project_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['category', 'status'], name='project_cat_status_idx'),
        ),
    ]
