# Generated by Django 5.2.16 on 2026-08-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='case_study',
            field=models.JSONField(blank=True, default=dict, help_text="Structured case-study content (may hold localized values): challenge, objectives, solution_approach, architecture, implementation_stages, results. Each value may be a localized object {'fa': ..., 'en': ..., 'ar': ...}."),
        ),
    ]
