# Generated by Django 5.2.16 on 2026-08-03 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_library', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('title_fa', models.CharField(blank=True, max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('title_ar', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(allow_unicode=True, help_text='URL identifier; Unicode (Arabic/Persian) characters are allowed.', max_length=255, unique=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('description_fa', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=255)),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_section_covers', to='media_library.mediafile')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service section',
                'verbose_name_plural': 'Service sections',
                'ordering': ['sort_order', 'title_en'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('title_fa', models.CharField(blank=True, max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('title_ar', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(allow_unicode=True, help_text='URL identifier; Unicode (Arabic/Persian) characters are allowed.', max_length=255, unique=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('short_description_fa', models.TextField(blank=True)),
                ('short_description_en', models.TextField(blank=True)),
                ('short_description_ar', models.TextField(blank=True)),
                ('description_fa', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_public', models.BooleanField(db_index=True, default=True)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('meta_title', models.CharField(blank=True, help_text='Recommended length: 60 characters.', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='Recommended length: 155 characters.', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('canonical_url', models.URLField(blank=True, max_length=500)),
                ('icon', models.CharField(blank=True, max_length=255)),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_covers', to='media_library.mediafile')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('og_image', models.ForeignKey(blank=True, help_text='OpenGraph sharing image.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_og_images', to='media_library.mediafile')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='services.servicesection')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['sort_order', 'title_en'],
                'indexes': [models.Index(fields=['status', 'is_public', 'published_at'], name='service_pub_idx'), models.Index(fields=['section', 'status'], name='service_section_status_idx')],
            },
        ),
    ]
