# Generated by Django 5.2.16 on 2026-08-08 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_builder', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesection',
            name='section_type',
            field=models.CharField(choices=[('hero', 'Hero'), ('statistics', 'Statistics'), ('services', 'Services'), ('erp', 'ERP (hanRP)'), ('projects', 'Projects'), ('articles', 'Articles'), ('about', 'About'), ('team', 'Team'), ('timeline', 'Timeline'), ('partners', 'Partners'), ('testimonials', 'Testimonials'), ('faq', 'FAQ'), ('cta', 'CTA'), ('footer', 'Footer'), ('journey', 'Service Journey'), ('comparison', 'Comparison'), ('stack', 'Technology Stack'), ('process', 'Process'), ('featured_projects', 'Featured Projects'), ('project_filters', 'Project Discovery'), ('technology_explorer', 'Technology Explorer'), ('projects_timeline', 'Project Timeline'), ('case_hero', 'Case Study Hero'), ('case_challenge', 'Case Study Challenge'), ('case_objectives', 'Case Study Objectives'), ('case_solution', 'Case Study Solution'), ('case_architecture', 'Case Study Architecture'), ('case_technology', 'Case Study Technology'), ('case_journey', 'Case Study Journey'), ('case_gallery', 'Case Study Gallery'), ('case_results', 'Case Study Results'), ('case_related_projects', 'Case Study Related Projects'), ('case_related_articles', 'Case Study Related Articles'), ('case_cta', 'Case Study CTA'), ('articles_hero', 'Articles Hero'), ('featured_article', 'Featured Article'), ('latest_articles', 'Latest Articles'), ('article_filters', 'Article Discovery'), ('category_explorer', 'Category Explorer'), ('tag_explorer', 'Tag Explorer'), ('newsletter_cta', 'Newsletter CTA'), ('article_cta', 'Article CTA'), ('article_hero', 'Article Hero'), ('article_content', 'Article Content'), ('article_related', 'Article Related Content')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sectionconfiguration',
            name='section_type',
            field=models.CharField(choices=[('hero', 'Hero'), ('statistics', 'Statistics'), ('services', 'Services'), ('erp', 'ERP (hanRP)'), ('projects', 'Projects'), ('articles', 'Articles'), ('about', 'About'), ('team', 'Team'), ('timeline', 'Timeline'), ('partners', 'Partners'), ('testimonials', 'Testimonials'), ('faq', 'FAQ'), ('cta', 'CTA'), ('footer', 'Footer'), ('journey', 'Service Journey'), ('comparison', 'Comparison'), ('stack', 'Technology Stack'), ('process', 'Process'), ('featured_projects', 'Featured Projects'), ('project_filters', 'Project Discovery'), ('technology_explorer', 'Technology Explorer'), ('projects_timeline', 'Project Timeline'), ('case_hero', 'Case Study Hero'), ('case_challenge', 'Case Study Challenge'), ('case_objectives', 'Case Study Objectives'), ('case_solution', 'Case Study Solution'), ('case_architecture', 'Case Study Architecture'), ('case_technology', 'Case Study Technology'), ('case_journey', 'Case Study Journey'), ('case_gallery', 'Case Study Gallery'), ('case_results', 'Case Study Results'), ('case_related_projects', 'Case Study Related Projects'), ('case_related_articles', 'Case Study Related Articles'), ('case_cta', 'Case Study CTA'), ('articles_hero', 'Articles Hero'), ('featured_article', 'Featured Article'), ('latest_articles', 'Latest Articles'), ('article_filters', 'Article Discovery'), ('category_explorer', 'Category Explorer'), ('tag_explorer', 'Tag Explorer'), ('newsletter_cta', 'Newsletter CTA'), ('article_cta', 'Article CTA'), ('article_hero', 'Article Hero'), ('article_content', 'Article Content'), ('article_related', 'Article Related Content')], max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('locale', models.CharField(choices=[('fa', 'Persian'), ('en', 'English'), ('ar', 'Arabic')], default='en', max_length=5)),
                ('source', models.CharField(blank=True, help_text='Where the signup happened (e.g. articles-newsletter).', max_length=100)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Newsletter subscription',
                'verbose_name_plural': 'Newsletter subscriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
