# Generated by Django 5.2.16 on 2026-08-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_builder', '0002_alter_pagesection_section_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscription',
            name='unsubscribe_token',
            field=models.CharField(blank=True, db_index=True, default='', help_text='One-click unsubscribe token.', max_length=64),
        ),
        migrations.AddField(
            model_name='newslettersubscription',
            name='unsubscribed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='section_type',
            field=models.CharField(choices=[('hero', 'Hero'), ('statistics', 'Statistics'), ('services', 'Services'), ('erp', 'ERP (hanRP)'), ('projects', 'Projects'), ('articles', 'Articles'), ('about', 'About'), ('team', 'Team'), ('timeline', 'Timeline'), ('partners', 'Partners'), ('testimonials', 'Testimonials'), ('faq', 'FAQ'), ('cta', 'CTA'), ('footer', 'Footer'), ('journey', 'Service Journey'), ('comparison', 'Comparison'), ('stack', 'Technology Stack'), ('process', 'Process'), ('featured_projects', 'Featured Projects'), ('project_filters', 'Project Discovery'), ('technology_explorer', 'Technology Explorer'), ('projects_timeline', 'Project Timeline'), ('case_hero', 'Case Study Hero'), ('case_challenge', 'Case Study Challenge'), ('case_objectives', 'Case Study Objectives'), ('case_solution', 'Case Study Solution'), ('case_architecture', 'Case Study Architecture'), ('case_technology', 'Case Study Technology'), ('case_journey', 'Case Study Journey'), ('case_gallery', 'Case Study Gallery'), ('case_results', 'Case Study Results'), ('case_related_projects', 'Case Study Related Projects'), ('case_related_articles', 'Case Study Related Articles'), ('case_cta', 'Case Study CTA'), ('articles_hero', 'Articles Hero'), ('featured_article', 'Featured Article'), ('latest_articles', 'Latest Articles'), ('article_filters', 'Article Discovery'), ('category_explorer', 'Category Explorer'), ('tag_explorer', 'Tag Explorer'), ('newsletter_cta', 'Newsletter CTA'), ('article_cta', 'Article CTA'), ('article_hero', 'Article Hero'), ('article_content', 'Article Content'), ('article_related', 'Article Related Content'), ('company_story', 'Company Story'), ('values', 'Company Values'), ('offices', 'Offices'), ('social_links', 'Social Links'), ('contact_form', 'Contact Form')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sectionconfiguration',
            name='section_type',
            field=models.CharField(choices=[('hero', 'Hero'), ('statistics', 'Statistics'), ('services', 'Services'), ('erp', 'ERP (hanRP)'), ('projects', 'Projects'), ('articles', 'Articles'), ('about', 'About'), ('team', 'Team'), ('timeline', 'Timeline'), ('partners', 'Partners'), ('testimonials', 'Testimonials'), ('faq', 'FAQ'), ('cta', 'CTA'), ('footer', 'Footer'), ('journey', 'Service Journey'), ('comparison', 'Comparison'), ('stack', 'Technology Stack'), ('process', 'Process'), ('featured_projects', 'Featured Projects'), ('project_filters', 'Project Discovery'), ('technology_explorer', 'Technology Explorer'), ('projects_timeline', 'Project Timeline'), ('case_hero', 'Case Study Hero'), ('case_challenge', 'Case Study Challenge'), ('case_objectives', 'Case Study Objectives'), ('case_solution', 'Case Study Solution'), ('case_architecture', 'Case Study Architecture'), ('case_technology', 'Case Study Technology'), ('case_journey', 'Case Study Journey'), ('case_gallery', 'Case Study Gallery'), ('case_results', 'Case Study Results'), ('case_related_projects', 'Case Study Related Projects'), ('case_related_articles', 'Case Study Related Articles'), ('case_cta', 'Case Study CTA'), ('articles_hero', 'Articles Hero'), ('featured_article', 'Featured Article'), ('latest_articles', 'Latest Articles'), ('article_filters', 'Article Discovery'), ('category_explorer', 'Category Explorer'), ('tag_explorer', 'Tag Explorer'), ('newsletter_cta', 'Newsletter CTA'), ('article_cta', 'Article CTA'), ('article_hero', 'Article Hero'), ('article_content', 'Article Content'), ('article_related', 'Article Related Content'), ('company_story', 'Company Story'), ('values', 'Company Values'), ('offices', 'Offices'), ('social_links', 'Social Links'), ('contact_form', 'Contact Form')], max_length=50, unique=True),
        ),
    ]
