# Generated by Django 5.2.16 on 2026-09-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationschedule',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('published', 'Published'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=20),
        ),
    ]
