# Generated by Django 5.2.16 on 2026-08-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_loginattempt_loginaudit_usersession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginaudit',
            name='event',
            field=models.CharField(choices=[('login', 'Login'), ('login_failed', 'Login failed'), ('logout', 'Logout'), ('refresh', 'Token refresh'), ('register', 'Account registered'), ('password_change', 'Password change'), ('password_reset', 'Password reset')], db_index=True, max_length=30),
        ),
    ]
