# Generated by Django 5.2.16 on 2026-08-03 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('file', models.FileField(upload_to='media/%Y/%m/')),
                ('original_name', models.CharField(blank=True, max_length=500)),
                ('alt_text_fa', models.CharField(blank=True, max_length=255)),
                ('alt_text_en', models.CharField(blank=True, max_length=255)),
                ('alt_text_ar', models.CharField(blank=True, max_length=255)),
                ('caption_fa', models.TextField(blank=True)),
                ('caption_en', models.TextField(blank=True)),
                ('caption_ar', models.TextField(blank=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('size', models.PositiveBigIntegerField(default=0, help_text='File size in bytes.')),
                ('width', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('height', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('is_public', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Media file',
                'verbose_name_plural': 'Media files',
                'ordering': ['-created_at'],
            },
        ),
    ]
