# Generated by Django 5.2.16 on 2026-08-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='title_ar',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='title_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='title_fa',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
